{
 "title": "gateway-monitor-tasks",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "time to first byte",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "gatewaymonitor_task_common_fetch_latency"
    }
   ]
  },
  {
   "title": "fetch speed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "gatewaymonitor_task_common_fetch_speed"
    }
   ]
  },
  {
   "title": "P95 time to first byte",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(gatewaymonitor_task_ipns_16777216_latency_bucket[24h])) by (le))"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(gatewaymonitor_task_ipns_268435456_latency_bucket[24h])) by (le))"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(gatewaymonitor_task_random_local_16777216_latency_bucket[24h])) by (le))"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(gatewaymonitor_task_random_local_268435456_latency_bucket[24h])) by (le))"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(gatewaymonitor_task_known_good_latency_bucket[24h])) by (le))"
    }
   ]
  },
  {
   "title": "P95 large fetch time",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(gatewaymonitor_task_ipns_268435456_fetch_time_bucket[24h])) by (le))"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(gatewaymonitor_task_random_local_268435456_fetch_time_bucket[24h])) by (le))"
    }
   ]
  },
  {
   "title": "P50 time to first byte",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(gatewaymonitor_task_ipns_16777216_latency_bucket[24h])) by (le))"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(gatewaymonitor_task_ipns_268435456_latency_bucket[24h])) by (le))"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(gatewaymonitor_task_random_local_16777216_latency_bucket[24h])) by (le))"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(gatewaymonitor_task_random_local_268435456_latency_bucket[24h])) by (le))"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(gatewaymonitor_task_known_good_latency_bucket[24h])) by (le))"
    }
   ]
  },
  {
   "title": "P50 large fetch time",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(gatewaymonitor_task_ipns_268435456_fetch_time_bucket[24h])) by (le))"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(gatewaymonitor_task_random_local_268435456_fetch_time_bucket[24h])) by (le))"
    }
   ]
  },
  {
   "title": "mean time to first byte (cached)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "gatewaymonitor_task_known_good_latency_sum / gatewaymonitor_task_known_good_latency_count"
    }
   ]
  },
  {
   "title": "This CID does not exist",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 },
   "collapsed": true,
   "panels": [
    {
     "title": "fetch time",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "gatewaymonitor_task_non_exist_fetch_time_bucket",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "error count",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "gatewaymonitor_task_non_exist_error_count"
      }
     ]
    },
    {
     "title": "time to first byte",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "gatewaymonitor_task_non_exsist_latency_bucket",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "fail count",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "gatewaymonitor_task_non_exist_fail_count"
      }
     ]
    }
   ]
  },
  { "title": "Known Good", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "fetch time",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "gatewaymonitor_task_known_good_fetch_time_bucket",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "error count",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "gatewaymonitor_task_known_good_error_count"
    }
   ]
  },
  {
   "title": "time to first byte",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "gatewaymonitor_task_known_good_latency_bucket",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "fail count",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "gatewaymonitor_task_known_good_fail_count"
    }
   ]
  },
  {
   "title": "IPNS small",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 },
   "collapsed": true,
   "panels": [
    {
     "title": "time to first byte",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "gatewaymonitor_task_ipns_16777216_latency_bucket",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Error Count",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "gatewaymonitor_task_ipns_16777216_error_count"
      }
     ]
    },
    {
     "title": "fetch time",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "gatewaymonitor_task_ipns_16777216_fetch_time_bucket",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "fail count",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "gatewaymonitor_task_ipns_16777216_fail_count"
      }
     ]
    },
    {
     "title": "IPNS publish time",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "gatewaymonitor_task_ipns_publish_bucket",
       "legendFormat": "{{le}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Random Local Large",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 51 },
   "collapsed": true,
   "panels": [
    {
     "title": "time to first byte",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "gatewaymonitor_task_random_local_268435456_latency_bucket",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "error count",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "gatewaymonitor_task_random_local_268435456_error_count"
      }
     ]
    },
    {
     "title": "fetch time",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "gatewaymonitor_task_random_local_268435456_fetch_time_bucket",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "fail count",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "gatewaymonitor_task_random_local_268435456_fail_count"
      }
     ]
    }
   ]
  },
  { "title": "Random Local Small", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 52 } },
  {
   "title": "time to first byte",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 53 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "gatewaymonitor_task_random_local_16777216_latency_bucket",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "error count",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 53 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "gatewaymonitor_task_random_local_16777216_error_count"
    }
   ]
  },
  {
   "title": "fetch time",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 61 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "gatewaymonitor_task_random_local_16777216_fetch_time_bucket",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "fail count",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 61 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "gatewaymonitor_task_random_local_16777216_fail_count"
    }
   ]
  }
 ]
}