{
 "title": "gateway-monitor-itself",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "Task Queue", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "queue fail rate over 5m",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "rate(gatewaymonitor_queue_fails[5m])"
    }
   ]
  },
  {
   "title": "queue fail count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    { "expr": "gatewaymonitor_queue_fails" }
   ]
  },
  {
   "title": "queued tasks",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    { "expr": "gatewaymonitor_queue_length" }
   ]
  },
  { "title": "Task Errors", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "errors since last restart",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "gatewaymonitor_daemon_errors_count{}"
    }
   ]
  }
 ]
}